version: '3'
services:
  api:
    image: "macxxn/dragonfly:latest"
    ports:
     - "2906:2906"
    environment:
     - DB_SERVER=db
     - DB_PORT=27017
    depends_on:
     - 'db'
  db:
    image: "mongo"
    ports:
     - "29019:27017"